[project]
name = "sc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Engr Rida", email = "ridamahmood175@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.65.0",
]

[project.scripts]
sc = "sc:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
